import type { NewsroomData, Story } from "./types";

const iso = (value: string) => new Date(value).toISOString();

function story(partial: Story): Story {
  return partial;
}

export function createSeed(): NewsroomData {
  const categories = [
    { id: "cat-politics", name: "سیاست", description: "نهادهای عمومی و تصمیم‌های شهری و ملی" },
    { id: "cat-economy", name: "اقتصاد", description: "بازار، تولید و معیشت" },
    { id: "cat-sports", name: "ورزش", description: "رقابت، باشگاه و ورزش همگانی" },
    { id: "cat-culture", name: "فرهنگ و هنر", description: "کتاب، سینما، موسیقی و نمایشگاه" },
    { id: "cat-science", name: "علم و فناوری", description: "پژوهش، فضا و ابزارهای تازه" },
    { id: "cat-society", name: "جامعه", description: "شهر، خدمات و زندگی روزمره" },
  ];
  const roleIds = ["publisher", "chief", "reporter"] as const;
  const access = roleIds.flatMap((roleId) =>
    categories.map((category) => ({
      roleId,
      categoryId: category.id,
      edit: !(roleId === "reporter" && category.id === "cat-politics"),
      publish: roleId !== "reporter",
    })),
  );

  return {
    currentRoleId: "reporter",
    sessionStartedAt: new Date().toISOString(),
    settings: {
      newsroomName: "اتاق خبر",
      tagline: "میز یکپارچه تولید و انتشار",
      pageSize: 20,
    },
    roles: [
      {
        id: "publisher",
        name: "مدیر مسئول",
        base: "publisher",
        permissions: { write: true, review: true, publish: true, archive: true, manageUsers: true, manageStructure: true },
      },
      {
        id: "chief",
        name: "سردبیر",
        base: "chief",
        permissions: { write: true, review: true, publish: false, archive: false, manageUsers: false, manageStructure: true },
      },
      {
        id: "reporter",
        name: "خبرنگار",
        base: "reporter",
        permissions: { write: true, review: false, publish: false, archive: false, manageUsers: false, manageStructure: false },
      },
    ],
    users: [
      { id: "u-leila", name: "لیلا نوری", username: "leila", roleId: "publisher", active: true },
      { id: "u-kamran", name: "کامران شفیعی", username: "kamran", roleId: "chief", active: true },
      { id: "u-sara", name: "سارا محمدی", username: "sara", roleId: "reporter", active: true },
      { id: "u-ali", name: "علی رضایی", username: "ali", roleId: "reporter", active: true },
      { id: "u-narges", name: "نرگس کاظمی", username: "narges", roleId: "reporter", active: true },
    ],
    access,
    categories,
    services: [
      { id: "srv-urgent", name: "فوری", description: "خبر کوتاه با اولویت بالا", active: true },
      { id: "srv-report", name: "گزارش", description: "شرح میدانی و پس‌زمینه", active: true },
      { id: "srv-talk", name: "گفت‌وگو", description: "مصاحبه و نقل‌قول", active: true },
      { id: "srv-multi", name: "چندرسانه‌ای", description: "عکس، ویدئو و صوت در کنار متن", active: true },
    ],
    steps: [
      { status: "draft", label: "پیش‌نویس", note: "خبرنگار متن را می‌نویسد و به میز ویرایش می‌فرستد." },
      { status: "editing", label: "ویرایش", note: "سردبیر لید، سندیت و تیتر را درست می‌کند." },
      { status: "review", label: "بازبینی", note: "سردبیر نسخه را برای انتشار تأیید یا برمی‌گرداند." },
      { status: "ready", label: "آماده انتشار", note: "خبر منتظر دستور مدیر مسئول است." },
      { status: "published", label: "منتشرشده", note: "خبر روی خروجی نشسته و در ترتیب صفحه جا دارد." },
      { status: "archived", label: "آرشیو", note: "از خروجی برداشته شده و برای سابقه مانده است." },
    ],
    transitions: [
      { id: "t-edit", from: "draft", to: "editing", label: "ارسال به ویرایش", actor: "reporter", enabled: true },
      { id: "t-skip", from: "draft", to: "review", label: "ارسال به بازبینی", actor: "reporter", enabled: true },
      { id: "t-review", from: "editing", to: "review", label: "ارسال به بازبینی", actor: "chief", enabled: true },
      { id: "t-back-draft", from: "editing", to: "draft", label: "بازگشت به خبرنگار", actor: "chief", enabled: true },
      { id: "t-ready", from: "review", to: "ready", label: "تأیید برای انتشار", actor: "chief", enabled: true },
      { id: "t-back-edit", from: "review", to: "editing", label: "بازگشت به ویرایش", actor: "chief", enabled: true },
      { id: "t-publish", from: "ready", to: "published", label: "انتشار", actor: "publisher", enabled: true },
      { id: "t-back-review", from: "ready", to: "review", label: "بازگشت به بازبینی", actor: "publisher", enabled: true },
      { id: "t-archive", from: "published", to: "archived", label: "انتقال به آرشیو", actor: "publisher", enabled: true },
      { id: "t-restore", from: "archived", to: "draft", label: "بازگشت به پیش‌نویس", actor: "publisher", enabled: true },
    ],
    homeOrder: ["s-karaj", "s-film", "s-bus"],
    stories: [
      story({
        id: "s-solar",
        title: "ظرفیت نیروگاه‌های خورشیدی یزد تا پایان سال دو برابر می‌شود",
        lead: "مدیرعامل برق منطقه‌ای یزد گفت با ورود چهار سایت تازه، توان تولید خورشیدی استان تا اسفند به ۴۸۰ مگاوات می‌رسد.",
        body: "یزد در دو سال گذشته میزبان چند مزرعه خورشیدی کوچک بوده است. حالا شرکت برق منطقه‌ای می‌گوید زیرساخت اتصال به شبکه برای سایت‌های تازه آماده شده و پیمانکاران از آبان کار نصب پنل را شروع می‌کنند. مدیرعامل این برنامه را بخشی از جبران اوج مصرف تابستان آینده دانست و تأکید کرد زمان‌بندی هنوز به تأمین تجهیزات وابسته است.",
        cover: "dawn",
        imagePrompt: "",
        audioScript: "",
        categoryId: "cat-economy",
        serviceId: "srv-report",
        tags: ["انرژی", "یزد", "خورشیدی"],
        status: "draft",
        author: "سارا محمدی",
        views: 4,
        createdAt: iso("2026-09-25T06:10:00Z"),
        updatedAt: iso("2026-09-25T06:40:00Z"),
      }),
      story({
        id: "s-ink",
        title: "نمایشگاه «مرکب و سکوت» در موزه هنرهای معاصر گشایش یافت",
        lead: "چهل اثر از خوشنویسان جوان تا پایان مهر در موزه به نمایش درمی‌آید و سه‌شنبه‌ها نشست گفت‌وگو برگزار می‌شود.",
        body: "نمایشگاه با چهل اثر از خوشنویسان جوان گشایش یافت. موزه اعلام کرد بازدید تا پایان مهر هر روز از ساعت ده تا هجده برقرار است. مسئول برگزاری گفت هدف نمایش، دیدن خط معاصر بیرون از قاب مسابقه است و فروش اثر در برنامه این دوره نیست.",
        cover: "ink",
        imagePrompt: "",
        audioScript: "",
        categoryId: "cat-culture",
        serviceId: "srv-talk",
        tags: ["خوشنویسی", "موزه"],
        status: "draft",
        author: "علی رضایی",
        views: 2,
        createdAt: iso("2026-09-25T05:00:00Z"),
        updatedAt: iso("2026-09-25T05:20:00Z"),
      }),
      story({
        id: "s-volley",
        title: "ایران در دیدار تدارکاتی والیبال از برزیل جلو افتاد",
        lead: "تیم ملی ست نخست را ۲۵ بر ۲۲ برد و سرمربی ترکیب بازی هفته بعد را هنوز قطعی ندانست.",
        body: "تیم ملی در ست نخست با نتیجه ۲۵ بر ۲۲ پیش افتاد. سرمربی تعویض‌ها را محتاطانه خواند و گفت ترکیب اصلی برای مسابقه هفته بعد هنوز قطعی نیست. سالن میزبان اعلام کرد بلیت ست‌های باقی‌مانده همچنان در گیشه است.",
        cover: "sea",
        imagePrompt: "",
        audioScript: "",
        categoryId: "cat-sports",
        serviceId: "srv-urgent",
        tags: ["والیبال", "تیم ملی"],
        status: "editing",
        author: "نرگس کاظمی",
        views: 18,
        createdAt: iso("2026-09-24T14:00:00Z"),
        updatedAt: iso("2026-09-24T16:10:00Z"),
      }),
      story({
        id: "s-tajrish",
        title: "بهسازی پیاده‌روهای بازار تجریش از هفته آینده آغاز می‌شود",
        lead: "شهرداری منطقه یک می‌گوید سنگفرش آسیب‌دیده از ابتدای بازار تا میدان عوض می‌شود و مسیر عابران جدا شده است.",
        body: "شهرداری منطقه یک اعلام کرد سنگفرش آسیب‌دیده از ابتدای بازار تا میدان تجریش تعویض می‌شود. کسبه خواسته‌اند کار شبانه باشد تا رفت‌وآمد روزانه تعطیل نشود. معاون عمران گفت برنامه شبانه در دست بررسی است و مسیر جایگزین برای عابران مشخص شده است.",
        cover: "sand",
        imagePrompt: "",
        audioScript: "",
        categoryId: "cat-society",
        serviceId: "srv-report",
        tags: ["تجریش", "شهرداری"],
        status: "editing",
        author: "سارا محمدی",
        views: 11,
        createdAt: iso("2026-09-24T08:00:00Z"),
        updatedAt: iso("2026-09-24T12:30:00Z"),
      }),
      story({
        id: "s-sat",
        title: "ماهواره «پارس ۲» در مدار زمین قرار گرفت",
        lead: "سازمان فضایی گفت ماهواره‌بر داخلی بامداد دیروز ماهواره را در مدار گذاشت و نخستین سیگنال دریافت شد.",
        body: "ماهواره بامداد دیروز با ماهواره‌بر داخلی به مدار رفت و نخستین سیگنال را فرستاد. سازمان فضایی گفت داده‌های سنجش از دور پس از کالیبراسیون در اختیار مراکز پژوهشی قرار می‌گیرد. مدیر پروژه زمان انتشار نخستین تصویر را هفته آینده اعلام کرد.",
        cover: "sea",
        imagePrompt: "عکس مستند از سکوی پرتاب در روشنایی بامداد، بدون نشان",
        audioScript: "",
        categoryId: "cat-science",
        serviceId: "srv-urgent",
        tags: ["ماهواره", "فضا"],
        status: "review",
        author: "علی رضایی",
        views: 40,
        createdAt: iso("2026-09-23T20:00:00Z"),
        updatedAt: iso("2026-09-25T04:10:00Z"),
      }),
      story({
        id: "s-food",
        title: "تورم ماهانه خوراکی‌ها برای دومین ماه پیاپی کم شد",
        lead: "مرکز آمار می‌گوید رشد ماهانه خوراکی‌ها کندتر شده، اما گروه گوشت هنوز بالاتر از میانگین سال است.",
        body: "مرکز آمار اعلام کرد شاخص خوراکی‌ها در ماه گذشته نسبت به ماه قبل رشد کمتری داشته است. کارشناسان این تغییر را شکننده می‌دانند و هشدار می‌دهند گروه گوشت هنوز بالاتر از میانگین سال حرکت می‌کند. گزارش کامل عصر امروز روی خروجی اقتصاد می‌نشیند.",
        cover: "dawn",
        imagePrompt: "",
        audioScript: "",
        categoryId: "cat-economy",
        serviceId: "srv-report",
        tags: ["تورم", "خوراکی"],
        status: "ready",
        author: "نرگس کاظمی",
        views: 22,
        createdAt: iso("2026-09-22T09:00:00Z"),
        updatedAt: iso("2026-09-25T03:00:00Z"),
      }),
      story({
        id: "s-karaj",
        title: "مجموعه ورزشی انقلاب کرج پس از نوسازی بازگشایی شد",
        lead: "سالن چندمنظوره و استخر تمرین پس از چهارده ماه کار دوباره باز است و عضویت محله‌ای از هفته بعد شروع می‌شود.",
        body: "مجموعه پس از چهارده ماه نوسازی با سالن چندمنظوره و استخر تمرین بازگشایی شد. مدیر مجموعه گفت عضویت محله‌ای از هفته آینده آغاز می‌شود و سانس بانوان طبق برنامه پیشین حفظ شده است. شهرداری کرج هزینه را از ردیف عمران ورزشی اعلام کرد.",
        cover: "pine",
        imagePrompt: "",
        audioScript: "",
        categoryId: "cat-sports",
        serviceId: "srv-report",
        tags: ["کرج", "ورزش همگانی"],
        status: "published",
        author: "سارا محمدی",
        views: 1284,
        createdAt: iso("2026-09-18T08:00:00Z"),
        updatedAt: iso("2026-09-20T10:00:00Z"),
        publishedAt: iso("2026-09-20T10:00:00Z"),
      }),
      story({
        id: "s-film",
        title: "خانه هنرمندان میزبان هفته فیلم کوتاه است",
        lead: "بیست فیلم کوتاه از شهرستان‌ها اکران می‌شود و امسال بخش نقد مردمی هم به برنامه اضافه شده است.",
        body: "هفته فیلم کوتاه با نمایش بیست اثر از شهرستان‌ها آغاز شد. دبیر جشنواره گفت امسال بخش نقد مردمی هم به برنامه اضافه شده و بلیت‌ها در سایت خانه هنرمندان است. نشست فیلم‌سازان اول هر عصر پس از آخرین سانس برگزار می‌شود.",
        cover: "ink",
        imagePrompt: "سالن نیمه‌روشن سینما، صندلی‌های پارچه‌ای، نور گرم پروژکتور",
        audioScript: "",
        categoryId: "cat-culture",
        serviceId: "srv-multi",
        tags: ["فیلم کوتاه", "خانه هنرمندان"],
        status: "published",
        author: "علی رضایی",
        views: 860,
        createdAt: iso("2026-09-19T11:00:00Z"),
        updatedAt: iso("2026-09-21T15:00:00Z"),
        publishedAt: iso("2026-09-21T15:00:00Z"),
      }),
      story({
        id: "s-bus",
        title: "لایحه حمایت از حمل‌ونقل عمومی در شورا بررسی شد",
        lead: "لایحه نوسازی ناوگان و اولویت مسیرهای کم‌برخوردار به جلسه علنی بعد موکول شد.",
        body: "لایحه برای نوسازی ناوگان فرسوده و اولویت مسیرهای کم‌برخوردار به شورا رفت. دو عضو شورا خواستار پیوست مالی روشن شدند و بررسی به جلسه علنی بعد موکول شد. معاون حمل‌ونقل گفت تا آن جلسه عدد دقیق اتوبوس‌های از رده خارج را می‌آورد.",
        cover: "sand",
        imagePrompt: "",
        audioScript: "",
        categoryId: "cat-politics",
        serviceId: "srv-report",
        tags: ["حمل‌ونقل", "شورای شهر"],
        status: "published",
        author: "نرگس کاظمی",
        views: 640,
        createdAt: iso("2026-09-20T07:30:00Z"),
        updatedAt: iso("2026-09-22T09:40:00Z"),
        publishedAt: iso("2026-09-22T09:40:00Z"),
      }),
      story({
        id: "s-rain",
        title: "گزارش تصویری بارش‌های بهاری در دامنه‌های البرز",
        lead: "بهار پارسال چند هفته پوشش گیاهی دامنه‌ها را سبز کرد. این فایل فقط در آرشیو میز جامعه مانده است.",
        body: "بهار پارسال بارش در دامنه‌های البرز پوشش گیاهی را برای چند هفته سبز کرد. این گزارش تصویری از آرشیو میز جامعه بازگردانده نشده و فقط برای سابقه در آرشیو مانده است. عکس‌ها در آلبوم باران نگهداری می‌شوند.",
        cover: "pine",
        imagePrompt: "",
        audioScript: "",
        categoryId: "cat-society",
        serviceId: "srv-multi",
        tags: ["البرز", "باران"],
        status: "archived",
        author: "علی رضایی",
        views: 2100,
        createdAt: iso("2026-05-12T08:00:00Z"),
        updatedAt: iso("2026-09-01T08:00:00Z"),
        publishedAt: iso("2026-05-12T12:00:00Z"),
      }),
    ],
    submissions: [
      {
        id: "sub-book",
        title: "ثبت‌نام نمایشگاه کتاب استانی در یزد از شنبه شروع می‌شود",
        lead: "اداره فرهنگ و ارشاد یزد زمان غرفه‌بندی را اعلام کرد.",
        body: "ثبت‌نام ناشران از شنبه در سامانه استانی باز می‌شود و نمایشگاه اواخر مهر در محل دائمی برگزار خواهد شد. هنوز فهرست مهمان‌ها نهایی نیست.",
        categoryId: "cat-culture",
        author: "علی رضایی",
        status: "new",
        note: "",
        createdAt: iso("2026-09-25T07:00:00Z"),
      },
      {
        id: "sub-metro",
        title: "شایعه تعطیلی خط مترو",
        lead: "پیام‌های فضای مجازی از تعطیلی یک خط خبر می‌دهند.",
        body: "متن ارسالی منبع رسمی ندارد و با اعلام شرکت بهره‌برداری هم‌خوان نیست.",
        categoryId: "cat-society",
        author: "سارا محمدی",
        status: "rejected",
        note: "منبع نامعتبر است و خبر تأیید نشده.",
        createdAt: iso("2026-09-23T18:00:00Z"),
      },
    ],
    suggestions: [
      {
        id: "sug-film",
        storyId: "s-film",
        serviceId: "srv-urgent",
        note: "اکران افتتاحیه را برای سرویس فوری فرهنگ هم بگذارید.",
        status: "pending",
        createdAt: iso("2026-09-24T19:00:00Z"),
      },
      {
        id: "sug-karaj",
        storyId: "s-karaj",
        serviceId: "srv-multi",
        note: "گزارش تصویری مجموعه به سرویس چندرسانه‌ای رفت.",
        status: "accepted",
        createdAt: iso("2026-09-21T11:00:00Z"),
      },
    ],
    albums: [
      {
        id: "alb-film",
        title: "هفته فیلم کوتاه",
        description: "سالن، پوستر و گفت‌وگوی حاشیه‌ای شب افتتاح.",
        photos: [
          { id: "ph-1", caption: "سالن اصلی پیش از سانس اول", src: "ink" },
          { id: "ph-2", caption: "پوستر ورودی", src: "dawn" },
          { id: "ph-3", caption: "میز گفت‌وگو", src: "sand" },
        ],
      },
      {
        id: "alb-karaj",
        title: "بازگشایی مجموعه کرج",
        description: "سالن نوسازی‌شده و استخر تمرین.",
        photos: [
          { id: "ph-4", caption: "سالن چندمنظوره", src: "pine" },
          { id: "ph-5", caption: "ورودی مجموعه", src: "sea" },
        ],
      },
    ],
    videos: [
      {
        id: "vid-karaj",
        title: "بازدید از سالن نوسازی‌شده کرج",
        url: "https://example.com/video/karaj",
        duration: "۰۲:۱۰",
        summary: "تصویر تمرینی از سالن، بدون مصاحبه.",
        published: true,
      },
      {
        id: "vid-sat",
        title: "توضیح کوتاه پرتاب پارس ۲",
        url: "https://example.com/video/pars",
        duration: "۰۱:۰۵",
        summary: "قطعه خام؛ هنوز برای انتشار تأیید نشده.",
        published: false,
      },
    ],
    feeds: [
      {
        id: "feed-science",
        title: "نمونه خوراک علم",
        url: "https://example.com/rss/science",
        items: [
          { id: "fi-1", title: "آزمایش میدانی شبکه لرزه‌نگاری در شرق تهران", summary: "نمونه محلی. از منبع زنده خوانده نشده است." },
          { id: "fi-2", title: "گزارش آزمایشگاهی درباره باتری‌های سدیمی", summary: "عنوان تمرینی برای انتقال به کارتابل." },
        ],
      },
    ],
    subscribers: [
      { id: "subr-1", name: "مریم احمدی", email: "maryam@example.com", active: true },
      { id: "subr-2", name: "حسین مرادی", email: "hossein@example.com", active: true },
      { id: "subr-3", name: "نگار شمس", email: "negar@example.com", active: false },
    ],
    issues: [
      {
        id: "iss-1",
        subject: "صبح خبر؛ پنجشنبه",
        body: "تیتر یک: بازگشایی مجموعه کرج. در فرهنگ، هفته فیلم کوتاه شروع شده است.",
        status: "draft",
        createdAt: iso("2026-09-25T05:30:00Z"),
      },
    ],
    social: [
      {
        id: "soc-1",
        channel: "تلگرام",
        text: "خانه هنرمندان میزبان هفته فیلم کوتاه است. بیست اثر از شهرستان‌ها اکران می‌شود.",
        storyId: "s-film",
        status: "draft",
        createdAt: iso("2026-09-21T16:00:00Z"),
      },
    ],
    mail: [
      {
        id: "mail-1",
        folder: "inbox",
        from: "reader@example.com",
        to: "desk@newsroom.local",
        subject: "اصلاح نام سالن در خبر کرج",
        body: "در پاراگراف دوم نام سالن قدیمی آمده است. نام تازه روی تابلو «انقلاب» است.",
        read: false,
        createdAt: iso("2026-09-22T08:12:00Z"),
      },
      {
        id: "mail-2",
        folder: "inbox",
        from: "photo@newsroom.local",
        to: "desk@newsroom.local",
        subject: "عکس‌های تجریش آماده است",
        body: "هشت فریم از پیاده‌رو در آلبوم شهر نشسته. برای گزارش انتخاب کنید.",
        read: true,
        createdAt: iso("2026-09-24T13:00:00Z"),
      },
      {
        id: "mail-3",
        folder: "outbox",
        from: "desk@newsroom.local",
        to: "archive@newsroom.local",
        subject: "درخواست سابقه بارش البرز",
        body: "فایل آرشیو بهار برای میز جامعه لازم است.",
        read: true,
        createdAt: iso("2026-09-01T09:00:00Z"),
      },
    ],
    people: [
      { id: "p-leila", name: "لیلا نوری", title: "مدیر مسئول", bio: "مسئول انتشار نهایی و پاسخ‌گویی محتوای خروجی.", kind: "مدیر مسئول", visible: true },
      { id: "p-kamran", name: "کامران شفیعی", title: "سردبیر", bio: "چینش خروجی و تأیید نسخه پیش از انتشار.", kind: "سردبیر", visible: true },
      { id: "p-sara", name: "سارا محمدی", title: "خبرنگار اقتصاد و جامعه", bio: "پوشش انرژی، شهر و خدمات شهری.", kind: "خبرنگار", visible: true },
      { id: "p-ali", name: "علی رضایی", title: "خبرنگار فرهنگ و علم", bio: "سینما، نمایشگاه و خبرهای علمی.", kind: "خبرنگار", visible: true },
      { id: "p-pouya", name: "پویا کرمی", title: "عکاس", bio: "عکاس میدانی میز جامعه و ورزش.", kind: "عکاس", visible: true },
    ],
    pages: [
      {
        id: "page-home",
        title: "صفحه ویژه هفته فرهنگ",
        blocks: [
          { id: "b1", type: "heading", text: "هفته فرهنگ در شهر", storyId: "" },
          { id: "b2", type: "text", text: "این صفحه محلی است و از بلوک‌های تحریریه چیده شده.", storyId: "" },
          { id: "b3", type: "story", text: "", storyId: "s-film" },
        ],
      },
    ],
    tables: [
      {
        id: "tbl-volley",
        title: "جدول تمرینی گروه والیبال",
        columns: ["تیم", "برد", "باخت", "امتیاز"],
        rows: [
          ["ایران", "۲", "۰", "۶"],
          ["برزیل", "۱", "۱", "۳"],
          ["ژاپن", "۰", "۲", "۰"],
        ],
      },
    ],
    banners: [
      { id: "bn-1", title: "هفته فیلم", text: "اکران رایگان سانس صبح در خانه هنرمندان", href: "/editorial/cartable/s-film", placement: "بالای صفحه", active: true },
      { id: "bn-2", title: "عضویت مجموعه کرج", text: "ثبت‌نام محله‌ای از شنبه", href: "/editorial/cartable/s-karaj", placement: "ستون", active: false },
    ],
    tickers: [
      { id: "tk-1", text: "ماهواره پارس ۲ سیگنال فرستاد؛ خبر در صف بازبینی است", active: true },
      { id: "tk-2", text: "بهسازی پیاده‌رو بازار تجریش از هفته آینده", active: true },
      { id: "tk-3", text: "سانس اضافه فیلم کوتاه برای عصر جمعه", active: false },
    ],
    events: [
      { id: "ev-1", title: "نشست فیلم‌سازان کوتاه", date: "2026-09-26", place: "خانه هنرمندان", note: "پس از سانس آخر" },
      { id: "ev-2", title: "بازدید میدانی تجریش", date: "2026-09-28", place: "بازار تجریش", note: "عکاس: پویا کرمی" },
      { id: "ev-3", title: "جلسه علنی شورا", date: "2026-10-02", place: "شورای شهر", note: "پیگیری لایحه حمل‌ونقل" },
      { id: "ev-4", title: "افتتاح سایت خورشیدی", date: "2026-10-06", place: "مهریز", note: "هماهنگی با برق منطقه‌ای" },
    ],
    tickets: [
      { id: "tk-photo", title: "دسترسی آلبوم شهر برای خبرنگار تازه‌کار", body: "لازم است علی رضایی هم آلبوم تجریش را ببیند.", status: "open", author: "سارا محمدی", createdAt: iso("2026-09-24T09:00:00Z") },
      { id: "tk-font", title: "فاصله تیتر در پیش‌نمایش صفحه", body: "در صفحه‌ساز، تیتر به متن چسبیده دیده می‌شود.", status: "pending", author: "کامران شفیعی", createdAt: iso("2026-09-23T11:20:00Z") },
      { id: "tk-desk", title: "پیشنهاد میز انرژی", body: "خبرهای خورشیدی بهتر است دسته جدا داشته باشند.", status: "closed", author: "لیلا نوری", createdAt: iso("2026-09-18T10:00:00Z") },
    ],
    notes: [
      { id: "nt-1", from: "کامران شفیعی", to: "سارا محمدی", body: "لید خبر یزد را کوتاه‌تر کن و عدد مگاوات را در تیتر نیاور اگر هنوز قطعی نیست.", read: false, createdAt: iso("2026-09-25T06:50:00Z") },
      { id: "nt-2", from: "لیلا نوری", to: "کامران شفیعی", body: "خبر خوراکی آماده انتشار است. عصر چک می‌کنم.", read: true, createdAt: iso("2026-09-25T03:20:00Z") },
    ],
    subsites: [
      { id: "site-sport", name: "ورزش", slug: "varzesh", active: true },
      { id: "site-province", name: "استان‌ها", slug: "ostanha", active: true },
    ],
    links: [
      { id: "ln-1", title: "درباره تحریریه", url: "/structure/pages", group: "پاصفحه" },
      { id: "ln-2", title: "تماس", url: "/audience/contact", group: "پاصفحه" },
      { id: "ln-3", title: "آرشیو", url: "/editorial/cartable?status=archived", group: "ستون" },
      { id: "ln-4", title: "خبرنامه", url: "/media/newsletter", group: "ستون" },
    ],
    logos: [
      { id: "lg-1", name: "نشانه اصلی", usage: "سرصفحه", color: "#8e1e2d" },
      { id: "lg-2", name: "تک‌رنگ تیره", usage: "چاپ", color: "#141210" },
      { id: "lg-3", name: "نسخه روشن", usage: "زمینه تیره", color: "#f3efe6" },
    ],
    forms: [
      { id: "fm-1", name: "تماس با تحریریه", fields: ["نام", "ایمیل", "پیام"], active: true },
      { id: "fm-2", name: "عضویت خبرنامه", fields: ["نام", "ایمیل"], active: true },
    ],
    menus: [
      { id: "mn-1", label: "سیاست", href: "/cat-politics" },
      { id: "mn-2", label: "اقتصاد", href: "/cat-economy" },
      { id: "mn-3", label: "ورزش", href: "/cat-sports" },
      { id: "mn-4", label: "فرهنگ", href: "/cat-culture" },
      { id: "mn-5", label: "علم", href: "/cat-science" },
      { id: "mn-6", label: "جامعه", href: "/cat-society" },
    ],
    portal: {
      url: "",
      note: "",
      enabled: false,
      lastCheck: "هنوز بررسی نشده است.",
    },
    comments: [
      { id: "c-1", storyId: "s-karaj", author: "رضا", body: "سانس بانوان در جدول سایت هنوز ساعت قدیمی را نشان می‌دهد.", status: "pending", createdAt: iso("2026-09-22T12:00:00Z") },
      { id: "c-2", storyId: "s-karaj", author: "هدی", body: "گزارش دقیق بود. کاش عکس ورودی هم بود.", status: "approved", createdAt: iso("2026-09-21T18:00:00Z") },
      { id: "c-3", storyId: "s-film", author: "کیوان", body: "فیلم شهرستان ما در فهرست نیست. اصلاح می‌کنید؟", status: "pending", createdAt: iso("2026-09-23T09:30:00Z") },
      { id: "c-4", storyId: "s-bus", author: "ناشناس", body: "این خبر تبلیغ یک شرکت خاص است.", status: "rejected", createdAt: iso("2026-09-22T11:00:00Z") },
      { id: "c-5", storyId: "s-film", author: "مینا", body: "نقد مردمی ایده خوبی است اگر وقت کافی باشد.", status: "approved", createdAt: iso("2026-09-23T20:00:00Z") },
    ],
    polls: [
      {
        id: "poll-1",
        question: "کدام قالب برای خبر فوری مناسب‌تر است؟",
        options: [
          { id: "op-1", label: "تیتر و دو خط", votes: 18 },
          { id: "op-2", label: "لید به‌اضافه نقل‌قول", votes: 11 },
          { id: "op-3", label: "متن کوتاه با ویدئو", votes: 7 },
        ],
        closed: false,
      },
    ],
    contacts: [
      { id: "ct-1", name: "شهرام نیک‌پی", email: "shahram@example.com", body: "برای مصاحبه درباره پیاده‌رو تجریش وقت می‌خواهم.", status: "new", createdAt: iso("2026-09-24T15:00:00Z") },
      { id: "ct-2", name: "کتابخانه محله", email: "lib@example.com", body: "پوستر هفته فیلم را برای تابلو می‌خواهیم.", status: "seen", createdAt: iso("2026-09-22T10:00:00Z") },
      { id: "ct-3", name: "فرهاد", email: "farhad@example.com", body: "خبر آرشیو باران را پیدا نمی‌کنم.", status: "closed", createdAt: iso("2026-09-12T10:00:00Z") },
    ],
    threads: [
      {
        id: "th-1",
        title: "تیتر خبر فوری چند کلمه باشد؟",
        posts: [
          { id: "fp-1", author: "کامران شفیعی", body: "برای فوری بیشتر از دوازده کلمه نروید مگر عدد ضروری باشد.", createdAt: iso("2026-09-20T09:00:00Z") },
          { id: "fp-2", author: "سارا محمدی", body: "در انرژی گاهی عدد همان خبر است. استثنا بماند؟", createdAt: iso("2026-09-20T09:40:00Z") },
        ],
      },
      {
        id: "th-2",
        title: "نام عکاس در آلبوم",
        posts: [
          { id: "fp-3", author: "پویا کرمی", body: "زیر هر فریم نام عکاس بیاید، نه فقط در توضیح آلبوم.", createdAt: iso("2026-09-21T14:00:00Z") },
        ],
      },
    ],
    activity: [
      { id: "act-1", at: iso("2026-09-25T06:40:00Z"), text: "پیش‌نویس خورشیدی یزد به‌روز شد" },
      { id: "act-2", at: iso("2026-09-25T04:10:00Z"), text: "خبر ماهواره به بازبینی رفت" },
      { id: "act-3", at: iso("2026-09-22T09:40:00Z"), text: "لایحه حمل‌ونقل منتشر شد" },
      { id: "act-4", at: iso("2026-09-20T10:00:00Z"), text: "خبر مجموعه کرج منتشر شد" },
    ],
  };
}

export function mergeSeed(raw: Partial<NewsroomData>): NewsroomData {
  const base = createSeed();
  const next: NewsroomData = { ...base };
  (Object.keys(base) as (keyof NewsroomData)[]).forEach((key) => {
    const value = raw[key];
    if (value !== undefined) next[key] = value as never;
  });
  if (!next.roles.some((role) => role.id === next.currentRoleId)) next.currentRoleId = "reporter";
  return next;
}
