import {
  DEFAULT_FEATURE_CATALOG,
  type FeatureModuleId,
  type PlatformAdmin,
} from './platformTypes'
import { defaultFeaturesFromCatalog } from '../lib/features'

const now = Date.now()
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString()

export const ALL_FEATURES: FeatureModuleId[] = DEFAULT_FEATURE_CATALOG.map((f) => f.id)

/** Defaults for newly created buildings (excludes unpaid add-ons). */
export function seedDefaultFeatures(): FeatureModuleId[] {
  return defaultFeaturesFromCatalog(DEFAULT_FEATURE_CATALOG)
}

export function createPlatformAdmin(): PlatformAdmin {
  return {
    featureCatalog: DEFAULT_FEATURE_CATALOG.map((e) => ({ ...e })),
    broadcasts: [
      {
        id: 'bc-1',
        title: 'قطع موقت آب مشاعات',
        body: 'فردا از ساعت ۸ تا ۱۲ آب مشاعات قطع است. مخزن را پر کنید.',
        createdByRole: 'complexManager',
        createdByName: 'مریم کاظمی',
        complexId: 'cpx-minoodar',
        audience: 'complex_members',
        startsAt: daysAgo(0),
        endsAt: new Date(now + 3 * 86400000).toISOString(),
        createdAt: daysAgo(0),
        active: true,
      },
      {
        id: 'bc-2',
        title: 'یادآوری شارژ ماه جاری',
        body: 'مدیران بلوک لطفاً وضعیت وصول شارژ را تا پایان هفته گزارش دهید.',
        createdByRole: 'siteAdmin',
        createdByName: 'ادمین کل سایت',
        audience: 'block_managers',
        startsAt: daysAgo(1),
        endsAt: new Date(now + 5 * 86400000).toISOString(),
        createdAt: daysAgo(1),
        active: true,
      },
      {
        id: 'bc-3',
        title: 'جلسه همسایگی بلوک',
        body: 'پنجشنبه ساعت ۱۸ در لابی — موضوع نظافت راهرو.',
        createdByRole: 'manager',
        createdByName: 'حسین توکلی',
        buildingId: 'bld-diyar',
        complexId: 'cpx-minoodar',
        audience: 'building_members',
        startsAt: daysAgo(0),
        endsAt: new Date(now + 2 * 86400000).toISOString(),
        createdAt: daysAgo(0),
        active: true,
      },
    ],
    sidePrograms: [
      {
        id: 'prg-1',
        scope: 'complex',
        complexId: 'cpx-minoodar',
        title: 'فروشگاه محلی مینودر',
        type: 'shop',
        description: 'راه‌اندازی غرفه مواد تازه در ورودی شهرک — هر پنجشنبه.',
        startsAt: new Date(now + 2 * 86400000).toISOString(),
        endsAt: new Date(now + 90 * 86400000).toISOString(),
        createdByName: 'مریم کاظمی',
        createdByRole: 'complexManager',
        status: 'upcoming',
      },
      {
        id: 'prg-2',
        scope: 'complex',
        complexId: 'cpx-minoodar',
        title: 'برنامه فرهنگی کودک',
        type: 'cultural',
        description: 'قصه‌گویی و نقاشی در سالن اجتماعات — جمعه‌ها ساعت ۱۰.',
        startsAt: daysAgo(7),
        endsAt: new Date(now + 60 * 86400000).toISOString(),
        createdByName: 'مریم کاظمی',
        createdByRole: 'complexManager',
        status: 'active',
      },
      {
        id: 'prg-3',
        scope: 'building',
        buildingId: 'bld-diyar',
        complexId: 'cpx-minoodar',
        title: 'اطلاع‌رسانی پارکینگ',
        type: 'announcement',
        description: 'شماره‌گذاری مجدد جای پارک و تخصیص موقت مهمان.',
        startsAt: daysAgo(1),
        endsAt: new Date(now + 14 * 86400000).toISOString(),
        createdByName: 'حسین توکلی',
        createdByRole: 'manager',
        status: 'active',
      },
    ],
    users: [
      {
        id: 'usr-admin',
        username: 'admin',
        password: 'admin123',
        role: 'siteAdmin',
        displayName: 'ادمین کل سایت',
        phone: '09120000001',
        status: 'active',
      },
      {
        id: 'usr-complex',
        username: 'complex',
        password: 'complex123',
        role: 'complexManager',
        displayName: 'مریم کاظمی',
        complexId: 'cpx-minoodar',
        phone: '09120000002',
        status: 'active',
      },
      {
        id: 'usr-manager',
        username: 'manager',
        password: 'manager123',
        role: 'manager',
        displayName: 'حسین توکلی',
        buildingId: 'bld-diyar',
        phone: '09120000003',
        status: 'active',
      },
      {
        id: 'usr-finance',
        username: 'finance',
        password: 'finance123',
        role: 'financeManager',
        displayName: 'سارا مالی',
        buildingId: 'bld-diyar',
        phone: '09120000004',
        status: 'active',
      },
    ],
    complexes: [
      {
        id: 'cpx-minoodar',
        name: 'شهرک مینودر',
        city: 'قزوین',
        managerName: 'مریم کاظمی',
        username: 'complex',
        password: 'complex123',
        blockIds: ['bld-diyar', 'bld-aftab'],
        status: 'active',
        subscriptionMonths: 12,
        subscriptionAmount: 2_400_000,
        subscriptionStatus: 'paid_demo',
        subscriptionExpiresAt: new Date(now + 200 * 86400000).toISOString(),
        subscriptionTracking: 'CPX-SUB-1001',
      },
    ],
    siteSuggestions: [
      {
        id: 'ssug-1',
        title: 'افزودن ماژول رزرو سالن',
        body: 'برای شهرک مینودر نیاز به رزرو سالن اجتماعات با تقویم شمسی داریم.',
        category: 'امکانات جدید',
        fromRole: 'complexManager',
        fromName: 'مریم کاظمی',
        fromUserId: 'usr-complex',
        complexId: 'cpx-minoodar',
        status: 'open',
        createdAt: daysAgo(2),
      },
      {
        id: 'ssug-2',
        title: 'تخفیف اشتراک بلوک‌های بالای ۲۰ واحد',
        body: 'پیشنهاد می‌کنم برای بلوک‌های پرجمعیت پلن اختصاصی تعریف شود.',
        category: 'تعرفه و اشتراک',
        fromRole: 'manager',
        fromName: 'حسین توکلی',
        fromUserId: 'usr-manager',
        buildingId: 'bld-diyar',
        complexId: 'cpx-minoodar',
        status: 'reviewing',
        createdAt: daysAgo(5),
      },
    ],
    otpChallenges: [],
    teams: [
      {
        id: 'team-elev',
        complexId: 'cpx-minoodar',
        name: 'تیم آسانسور',
        specialty: 'آسانسور و بالابر',
      },
      {
        id: 'team-elec',
        complexId: 'cpx-minoodar',
        name: 'تیم برق',
        specialty: 'برق مشاعات',
      },
      {
        id: 'team-clean',
        complexId: 'cpx-minoodar',
        name: 'تیم نظافت',
        specialty: 'نظافت و فضای سبز',
      },
    ],
    staff: [
      {
        id: 'stf-elec1',
        complexId: 'cpx-minoodar',
        name: 'رضا برق‌کار',
        specialty: 'برقکار',
        phone: '0912••••111',
        active: true,
      },
      {
        id: 'stf-mech1',
        complexId: 'cpx-minoodar',
        name: 'مهدی تاسیسات',
        specialty: 'تاسیسات',
        phone: '0912••••222',
        active: true,
      },
      {
        id: 'stf-contr1',
        complexId: 'cpx-minoodar',
        name: 'شرکت پیمانکار آریا',
        specialty: 'پیمانکار',
        phone: '021••••333',
        active: true,
      },
      {
        id: 'stf-elev1',
        complexId: 'cpx-minoodar',
        name: 'کاظم آسانسور',
        specialty: 'آسانسور',
        phone: '0912••••444',
        active: false,
      },
    ],
    tickets: [
      {
        id: 'tkt1',
        complexId: 'cpx-minoodar',
        buildingId: 'bld-diyar',
        category: 'آسانسور',
        title: 'صدای غیرعادی کابین',
        body: 'از هفته گذشته هنگام توقف طبقه ۲ صدای سایش شنیده می‌شود.',
        status: 'open',
        createdBy: 'حسین توکلی (مدیر بلوک)',
        createdAt: daysAgo(2),
        updatedAt: daysAgo(2),
      },
      {
        id: 'tkt2',
        complexId: 'cpx-minoodar',
        buildingId: 'bld-aftab',
        category: 'برق',
        title: 'خاموشی چراغ‌های حیاط',
        body: 'نیمی از چراغ‌های بلوک ب خاموش است؛ درخواست اعزام تیم برق.',
        status: 'in_progress',
        createdBy: 'علی رضایی (مدیر بلوک)',
        assignedTeamId: 'team-elec',
        assignedPersonId: 'stf-elec1',
        createdAt: daysAgo(5),
        updatedAt: daysAgo(1),
      },
      {
        id: 'tkt3',
        complexId: 'cpx-minoodar',
        buildingId: 'bld-diyar',
        category: 'نظافت',
        title: 'لکه روغن پارکینگ',
        body: 'لکه روغن در رمپ پارکینگ نیاز به پاکسازی تخصصی دارد.',
        status: 'resolved',
        createdBy: 'حسین توکلی (مدیر بلوک)',
        assignedTeamId: 'team-clean',
        createdAt: daysAgo(12),
        updatedAt: daysAgo(4),
        resolutionNote: 'تیم نظافت لکه را پاک کرد.',
      },
      {
        id: 'tkt4',
        complexId: 'cpx-minoodar',
        buildingId: 'bld-diyar',
        category: 'تاسیسات',
        title: 'نشتی شیر آب موتورخانه',
        body: 'نشتی جزئی از شیر اصلی موتورخانه؛ نیاز به اعزام تاسیساتی.',
        status: 'open',
        createdBy: 'حسین توکلی (مدیر بلوک)',
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
      },
    ],
    complexLedger: [
      {
        id: 'cl1',
        complexId: 'cpx-minoodar',
        kind: 'expense',
        category: 'برق',
        title: 'تعویض چراغ‌های حیاط بلوک آفتاب',
        amount: 4_500_000,
        note: 'ارجاع به رضا برق‌کار',
        buildingId: 'bld-aftab',
        at: daysAgo(3),
        createdBy: 'مدیر شهرک',
      },
      {
        id: 'cl2',
        complexId: 'cpx-minoodar',
        kind: 'expense',
        category: 'نظافت',
        title: 'پاکسازی رمپ پارکینگ',
        amount: 1_200_000,
        buildingId: 'bld-diyar',
        at: daysAgo(8),
        createdBy: 'مدیر شهرک',
      },
      {
        id: 'cl3',
        complexId: 'cpx-minoodar',
        kind: 'expense',
        category: 'پیمانکار',
        title: 'قرارداد نگهداری ماهانه مشاعات',
        amount: 8_000_000,
        note: 'شرکت پیمانکار آریا',
        at: daysAgo(15),
        createdBy: 'مدیر شهرک',
      },
      {
        id: 'cl4',
        complexId: 'cpx-minoodar',
        kind: 'income',
        category: 'سهم بلوک‌ها',
        title: 'سهم ماهانه مجتمع دیار',
        amount: 6_000_000,
        buildingId: 'bld-diyar',
        at: daysAgo(10),
        createdBy: 'مدیر شهرک',
      },
      {
        id: 'cl5',
        complexId: 'cpx-minoodar',
        kind: 'income',
        category: 'سهم بلوک‌ها',
        title: 'سهم ماهانه بلوک آفتاب',
        amount: 3_500_000,
        buildingId: 'bld-aftab',
        at: daysAgo(10),
        createdBy: 'مدیر شهرک',
      },
      {
        id: 'cl6',
        complexId: 'cpx-minoodar',
        kind: 'income',
        category: 'اجاره مشاعات',
        title: 'اجاره فضای تبلیغاتی لابی',
        amount: 2_000_000,
        at: daysAgo(20),
        createdBy: 'مدیر شهرک',
      },
    ],
    discounts: [
      {
        id: 'dc1',
        code: 'DIYAR20',
        percent: 20,
        maxUses: 50,
        usedCount: 3,
        active: true,
        note: 'تخفیف افتتاحیه',
      },
      {
        id: 'dc2',
        code: 'TOWER10',
        percent: 10,
        maxUses: 100,
        usedCount: 12,
        active: true,
        note: 'ویژه برج‌ها',
      },
    ],
    tariffs: [
      {
        id: 'tr1',
        name: 'کوچک',
        maxUnits: 10,
        monthlyPerUnit: 45_000,
        buildingTypes: ['block', 'building'],
      },
      {
        id: 'tr2',
        name: 'متوسط',
        maxUnits: 30,
        monthlyPerUnit: 38_000,
        buildingTypes: ['block', 'building', 'tower'],
      },
      {
        id: 'tr3',
        name: 'بزرگ',
        maxUnits: 80,
        monthlyPerUnit: 32_000,
        buildingTypes: ['building', 'tower'],
      },
      {
        id: 'tr4',
        name: 'برج',
        maxUnits: 9999,
        monthlyPerUnit: 28_000,
        buildingTypes: ['tower'],
      },
    ],
    subscriptionPayments: [
      {
        id: 'sp1',
        buildingId: 'bld-diyar',
        amount: 1_800_000,
        units: 4,
        months: 12,
        method: 'gateway',
        status: 'paid_demo',
        trackingCode: 'SUB-8821',
        createdAt: daysAgo(20),
      },
      {
        id: 'sp2',
        buildingId: 'bld-sepehr',
        amount: 12_500_000,
        units: 48,
        months: 6,
        discountCode: 'TOWER10',
        method: 'bank_receipt',
        status: 'pending',
        receiptNote: 'فیش کارت‌به‌کارت — بانک ملی',
        trackingCode: 'SUB-9910',
        createdAt: daysAgo(1),
      },
      {
        id: 'sp3',
        buildingId: 'bld-aftab',
        amount: 1_200_000,
        units: 12,
        months: 3,
        method: 'bank_receipt',
        status: 'approved',
        receiptNote: 'فیش آپلود‌شده توسط مدیر بلوک',
        trackingCode: 'SUB-7744',
        createdAt: daysAgo(8),
        reviewedAt: daysAgo(7),
        reviewedBy: 'مدیر بلوک آفتاب',
      },
      {
        id: 'sp4',
        buildingId: 'bld-diyar',
        amount: 540_000,
        units: 4,
        months: 3,
        method: 'gateway',
        status: 'paid_demo',
        trackingCode: 'SUB-3301',
        createdAt: daysAgo(100),
      },
      {
        id: 'sp5',
        buildingId: 'bld-aftab',
        amount: 2_400_000,
        units: 12,
        months: 6,
        method: 'gateway',
        status: 'pending',
        trackingCode: 'SUB-6612',
        createdAt: daysAgo(4),
        receiptNote: 'تمدید ۶ ماهه — در انتظار تأیید',
      },
      {
        id: 'sp6',
        buildingId: 'bld-sepehr',
        amount: 18_000_000,
        units: 48,
        months: 12,
        discountCode: 'TOWER10',
        method: 'bank_receipt',
        status: 'rejected',
        receiptNote: 'فیش ناخوانا — نیاز به ارسال مجدد',
        trackingCode: 'SUB-1200',
        createdAt: daysAgo(40),
        reviewedAt: daysAgo(38),
        reviewedBy: 'ادمین کل سایت',
      },
      {
        id: 'sp7',
        buildingId: 'bld-sepehr',
        amount: 9_000_000,
        units: 48,
        months: 6,
        method: 'gateway',
        status: 'paid_demo',
        trackingCode: 'SUB-5588',
        createdAt: daysAgo(180),
      },
      {
        id: 'sp8',
        buildingId: 'bld-aftab',
        amount: 1_100_000,
        units: 12,
        months: 3,
        method: 'bank_receipt',
        status: 'rejected',
        trackingCode: 'SUB-4490',
        createdAt: daysAgo(55),
        reviewedAt: daysAgo(54),
        reviewedBy: 'ادمین کل سایت',
        receiptNote: 'مبلغ ناقص',
      },
      {
        id: 'sp-addon-qarz-diyar',
        buildingId: 'bld-diyar',
        amount: 640_000,
        units: 1,
        months: 12,
        method: 'gateway',
        status: 'paid_demo',
        trackingCode: 'ADD-QARZ-01',
        createdAt: daysAgo(15),
        reviewedAt: daysAgo(15),
        reviewedBy: 'ادمین کل سایت',
        addonFeatureId: 'qarz',
        kind: 'feature_addon',
        receiptNote: 'خرید افزونه قرض‌الحسنه — ۱۲ ماهه',
      },
      {
        id: 'sp-addon-meet-aftab',
        buildingId: 'bld-aftab',
        amount: 150_000,
        units: 1,
        months: 3,
        method: 'bank_receipt',
        status: 'pending',
        trackingCode: 'ADD-MEET-02',
        createdAt: daysAgo(2),
        addonFeatureId: 'meetings',
        kind: 'feature_addon',
        receiptNote: 'درخواست افزونه جلسات — در انتظار تأیید فیش',
      },
      {
        id: 'sp-addon-chat-sepehr',
        buildingId: 'bld-sepehr',
        amount: 350_000,
        units: 1,
        months: 0,
        method: 'gateway',
        status: 'paid_demo',
        trackingCode: 'ADD-CHAT-03',
        createdAt: daysAgo(30),
        reviewedAt: daysAgo(30),
        reviewedBy: 'ادمین کل سایت',
        addonFeatureId: 'chat',
        kind: 'feature_addon',
        receiptNote: 'خرید یک‌بار چت داخلی',
      },
      {
        id: 'sp-cpx-minoodar',
        complexId: 'cpx-minoodar',
        amount: 2_400_000,
        units: 1,
        months: 12,
        method: 'gateway',
        status: 'paid_demo',
        trackingCode: 'CPX-SUB-1001',
        createdAt: daysAgo(60),
        reviewedAt: daysAgo(60),
        reviewedBy: 'ادمین کل سایت',
        kind: 'complex_platform',
        receiptNote: 'اشتراک پلتفرم مدیر شهرک مینودر — ۱۲ ماهه',
      },
      {
        id: 'sp-cpx-minoodar-old',
        complexId: 'cpx-minoodar',
        amount: 900_000,
        units: 1,
        months: 3,
        method: 'bank_receipt',
        status: 'approved',
        trackingCode: 'CPX-SUB-0880',
        createdAt: daysAgo(200),
        reviewedAt: daysAgo(198),
        reviewedBy: 'ادمین کل سایت',
        kind: 'complex_platform',
        receiptNote: 'دوره قبلی اشتراک مدیر شهرک',
      },
    ],
    sms: {
      enabled: false,
      endpoint: 'https://sms.example.com/api/send',
      apiKey: '',
      sender: 'DiyarSharj',
    },
    gateway: {
      mode: 'both',
      merchantId: '',
      callbackUrl: 'https://sharj.diyareminoodari.ir/pay/callback',
      bankAccountInfo: 'بانک ملت — شماره شبا IR00•••••••• — به نام دیارشارژ',
      enabled: true,
    },
    activity: [
      { id: 'act1', at: daysAgo(0), kind: 'login', label: 'ورود مدیر سایت', buildingId: undefined },
      { id: 'act2', at: daysAgo(1), kind: 'payment', label: 'فیش اشتراک برج سپهر ثبت شد', buildingId: 'bld-sepehr' },
      { id: 'act3', at: daysAgo(2), kind: 'ticket', label: 'تیکت آسانسور از دیار مینودری', buildingId: 'bld-diyar' },
      { id: 'act4', at: daysAgo(3), kind: 'qarz', label: 'صندوق قرض‌الحسنه در انتظار رأی', buildingId: 'bld-diyar' },
      { id: 'act5', at: daysAgo(4), kind: 'ticket', label: 'تیکت برق بلوک آفتاب به تیم ارجاع شد', buildingId: 'bld-aftab' },
      { id: 'act6', at: daysAgo(5), kind: 'sub', label: 'پرداخت اشتراک دیار مینودری', buildingId: 'bld-diyar' },
      { id: 'act7', at: daysAgo(6), kind: 'feature', label: 'فعال‌سازی ماژول پیشنهادات', buildingId: 'bld-aftab' },
      { id: 'act8', at: daysAgo(8), kind: 'payment', label: 'تأیید فیش اشتراک آفتاب', buildingId: 'bld-aftab' },
    ],
  }
}
