import type { AppState } from './types'

const now = Date.now()
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString()

export const STORAGE_KEY = 'diyarsharj-v1'

export function createSeed(): AppState {
  const units = [
    {
      id: 'u1',
      number: '۱۰۱',
      floor: 1,
      areaSqm: 95,
      occupants: 3,
      ownerName: 'رضا محمدی',
      residentName: 'رضا محمدی',
      parkingSpot: 'P-01',
      balance: -2_450_000,
    },
    {
      id: 'u2',
      number: '۱۰۲',
      floor: 1,
      areaSqm: 110,
      occupants: 4,
      ownerName: 'سارا احمدی',
      residentName: 'علی نوری',
      parkingSpot: 'P-02',
      balance: -1_100_000,
    },
    {
      id: 'u3',
      number: '۲۰۱',
      floor: 2,
      areaSqm: 88,
      occupants: 2,
      ownerName: 'مهدی کریمی',
      residentName: 'مهدی کریمی',
      parkingSpot: 'P-05',
      balance: 350_000,
    },
    {
      id: 'u4',
      number: '۲۰۲',
      floor: 2,
      areaSqm: 120,
      occupants: 5,
      ownerName: 'نازنین رضایی',
      residentName: 'حسین رضایی',
      parkingSpot: 'P-06',
      balance: -3_200_000,
    },
  ]

  return {
    buildingName: 'مجتمع دیار مینودری',
    fundBalance: 18_750_000,
    session: null,
    units,
    residents: [
      { id: 'r1', unitId: 'u1', name: 'رضا محمدی', phone: '0912••••101', roleInUnit: 'owner' },
      { id: 'r2', unitId: 'u2', name: 'سارا احمدی', phone: '0912••••102', roleInUnit: 'owner' },
      { id: 'r3', unitId: 'u2', name: 'علی نوری', phone: '0935••••220', roleInUnit: 'resident' },
      { id: 'r4', unitId: 'u3', name: 'مهدی کریمی', phone: '0913••••201', roleInUnit: 'owner' },
      { id: 'r5', unitId: 'u4', name: 'نازنین رضایی', phone: '0910••••202', roleInUnit: 'owner' },
      { id: 'r6', unitId: 'u4', name: 'حسین رضایی', phone: '0936••••330', roleInUnit: 'resident' },
    ],
    schedules: [
      {
        id: 's1',
        title: 'شارژ ماهانه ثابت',
        formula: 'fixed',
        amountOrRate: 1_500_000,
        dayOfMonth: 5,
        period: 'monthly',
        active: true,
        ownerSharePercent: 40,
        lastRunAt: daysAgo(12),
      },
      {
        id: 's2',
        title: 'شارژ متراژی مشاعات',
        formula: 'area',
        amountOrRate: 8_000,
        dayOfMonth: 1,
        period: 'monthly',
        active: true,
        ownerSharePercent: 70,
      },
      {
        id: 's3',
        title: 'شارژ نفری نظافت',
        formula: 'perPerson',
        amountOrRate: 120_000,
        dayOfMonth: 10,
        period: 'monthly',
        active: false,
        ownerSharePercent: 0,
      },
      {
        id: 's4',
        title: 'آب مصرفی فصلی',
        formula: 'consumption',
        amountOrRate: 15_000,
        dayOfMonth: 15,
        period: 'seasonal',
        active: true,
        ownerSharePercent: 50,
      },
    ],
    bills: [
      {
        id: 'b1',
        unitId: 'u1',
        title: 'شارژ مهر ۱۴۰۴',
        periodLabel: 'مهر ۱۴۰۴',
        total: 2_450_000,
        ownerShare: 980_000,
        residentShare: 1_470_000,
        paidOwner: 0,
        paidResident: 0,
        status: 'unpaid',
        createdAt: daysAgo(8),
        formula: 'fixed',
      },
      {
        id: 'b2',
        unitId: 'u2',
        title: 'شارژ مهر ۱۴۰۴',
        periodLabel: 'مهر ۱۴۰۴',
        total: 2_380_000,
        ownerShare: 1_666_000,
        residentShare: 714_000,
        paidOwner: 1_280_000,
        paidResident: 0,
        status: 'partial',
        createdAt: daysAgo(8),
        formula: 'area',
      },
      {
        id: 'b3',
        unitId: 'u3',
        title: 'شارژ شهریور ۱۴۰۴',
        periodLabel: 'شهریور ۱۴۰۴',
        total: 1_500_000,
        ownerShare: 600_000,
        residentShare: 900_000,
        paidOwner: 600_000,
        paidResident: 900_000,
        status: 'paid',
        createdAt: daysAgo(35),
        formula: 'fixed',
      },
      {
        id: 'b4',
        unitId: 'u4',
        title: 'شارژ مهر ۱۴۰۴',
        periodLabel: 'مهر ۱۴۰۴',
        total: 3_200_000,
        ownerShare: 2_240_000,
        residentShare: 960_000,
        paidOwner: 0,
        paidResident: 0,
        status: 'unpaid',
        createdAt: daysAgo(8),
        formula: 'area',
      },
    ],
    payments: [
      {
        id: 'p1',
        billId: 'b3',
        unitId: 'u3',
        amount: 1_500_000,
        party: 'owner',
        trackingCode: 'DS-4821-9033',
        createdAt: daysAgo(30),
        method: 'online-demo',
      },
    ],
    ledger: [
      {
        id: 'l1',
        kind: 'expense',
        category: 'نظافت',
        title: 'قرارداد نظافت مهر',
        amount: 4_200_000,
        note: 'شرکت خدماتی آبان',
        createdAt: daysAgo(6),
        visibleToResidents: true,
      },
      {
        id: 'l2',
        kind: 'expense',
        category: 'آسانسور',
        title: 'سرویس دوره‌ای آسانسور',
        amount: 2_800_000,
        note: 'قطعات یدکی + دستمزد',
        createdAt: daysAgo(14),
        visibleToResidents: true,
      },
      {
        id: 'l3',
        kind: 'income',
        category: 'شارژ',
        title: 'وصول شارژ شهریور',
        amount: 9_600_000,
        note: 'پرداخت‌های آنلاین و دستی',
        createdAt: daysAgo(28),
        visibleToResidents: true,
      },
      {
        id: 'l4',
        kind: 'expense',
        category: 'برق مشاعات',
        title: 'قبوض برق مشاعات',
        amount: 1_950_000,
        note: 'دوره شهریور',
        createdAt: daysAgo(20),
        visibleToResidents: true,
      },
      {
        id: 'l5',
        kind: 'income',
        category: 'اجاره پارکینگ مهمان',
        title: 'اجاره موقت پارکینگ',
        amount: 500_000,
        note: 'مهمان واحد ۲۰۱',
        createdAt: daysAgo(10),
        visibleToResidents: false,
      },
    ],
    polls: [
      {
        id: 'poll1',
        title: 'رنگ‌آمیزی راهروها',
        audience: 'residents',
        options: [
          { id: 'o1', label: 'موافقم', votes: 3 },
          { id: 'o2', label: 'مخالفم', votes: 1 },
          { id: 'o3', label: 'نیاز به بررسی بیشتر', votes: 2 },
        ],
        closesAt: daysAgo(-10),
        votedBy: [],
      },
      {
        id: 'poll2',
        title: 'تعویض درب ورودی اصلی',
        audience: 'owners',
        options: [
          { id: 'o1', label: 'مدل فلزی امنیتی', votes: 2 },
          { id: 'o2', label: 'مدل شیشه‌ای', votes: 1 },
          { id: 'o3', label: 'فعلاً نیاز نیست', votes: 0 },
        ],
        closesAt: daysAgo(-20),
        votedBy: [],
      },
    ],
    news: [
      {
        id: 'n1',
        title: 'قطع آب برای سرویس مخزن',
        body: 'فردا از ساعت ۱۰ تا ۱۲ قطع آب خواهیم داشت. مخازن را پر کنید.',
        createdAt: daysAgo(1),
      },
      {
        id: 'n2',
        title: 'جمع‌آوری زباله خشک',
        body: 'هر سه‌شنبه زباله خشک در حیاط جمع‌آوری می‌شود.',
        createdAt: daysAgo(4),
      },
    ],
    chat: [
      {
        id: 'c1',
        author: 'مدیر ساختمان',
        body: 'سلام — برای ثبت درخواست تعمیرات از همین بخش پیام بگذارید.',
        createdAt: daysAgo(2),
      },
      {
        id: 'c2',
        author: 'واحد ۱۰۲',
        body: 'چراغ راهرو طبقه اول سوخته است.',
        createdAt: daysAgo(1),
      },
    ],
    meetings: [
      {
        id: 'm1',
        title: 'جلسه هیئت‌مدیره مهر',
        scheduledAt: daysAgo(-5),
        place: 'لابی مجتمع',
        agenda: 'بررسی بودجه رنگ‌آمیزی و آسانسور',
        resolutions: [],
        attendees: [],
        notifiedAt: daysAgo(1),
        status: 'upcoming',
        createdAt: daysAgo(2),
        updatedAt: daysAgo(1),
      },
      {
        id: 'm2',
        title: 'جلسه عمومی ساکنین شهریور',
        scheduledAt: daysAgo(20),
        place: 'سالن اجتماعات',
        agenda: 'گزارش مالی تابستان و نظافت',
        resolutions: [
          'قرارداد نظافت با شرکت آبان تمدید شود.',
          'هزینه سرویس آسانسور از صندوق مشاعات پرداخت شود.',
        ],
        attendees: [
          { id: 'a1', name: 'رضا محمدی', residentId: 'r1', unitId: 'u1' },
          { id: 'a2', name: 'سارا احمدی', residentId: 'r2', unitId: 'u2' },
          { id: 'a3', name: 'مهدی کریمی', residentId: 'r4', unitId: 'u3' },
          { id: 'a4', name: 'مهمان — نماینده شهرداری', unitId: undefined },
        ],
        notifiedAt: daysAgo(25),
        status: 'done',
        createdAt: daysAgo(30),
        updatedAt: daysAgo(19),
      },
    ],
    notifications: [
      {
        id: 'nt1',
        title: 'یادآوری پرداخت شارژ',
        body: 'مهلت پرداخت شارژ مهر تا ۵ روز دیگر است.',
        createdAt: daysAgo(0),
        kind: 'reminder',
        read: false,
      },
      {
        id: 'nt2',
        title: 'نظرسنجی جدید',
        body: 'نظرسنجی «رنگ‌آمیزی راهروها» برای ساکنین باز شد.',
        createdAt: daysAgo(1),
        kind: 'poll',
        read: false,
      },
      {
        id: 'nt3',
        title: 'پیامک — به‌زودی',
        body: 'ارسال پیامک واقعی پس از اتصال درگاه پیامک فعال می‌شود.',
        createdAt: daysAgo(3),
        kind: 'sms-stub',
        read: true,
      },
    ],
  }
}
