import { FEATURE_CATALOG, type FeatureModuleId, type PlatformAdmin } from './platformTypes'

const now = Date.now()
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString()

export const ALL_FEATURES: FeatureModuleId[] = FEATURE_CATALOG.map((f) => f.id)

export function createPlatformAdmin(): PlatformAdmin {
  return {
    users: [
      {
        id: 'usr-admin',
        username: 'admin',
        password: 'admin123',
        role: 'siteAdmin',
        displayName: 'ادمین کل سایت',
        status: 'active',
      },
      {
        id: 'usr-complex',
        username: 'complex',
        password: 'complex123',
        role: 'complexManager',
        displayName: 'مریم کاظمی',
        complexId: 'cpx-minoodar',
        status: 'active',
      },
      {
        id: 'usr-manager',
        username: 'manager',
        password: 'manager123',
        role: 'manager',
        displayName: 'حسین توکلی',
        buildingId: 'bld-diyar',
        status: 'active',
      },
      {
        id: 'usr-finance',
        username: 'finance',
        password: 'finance123',
        role: 'financeManager',
        displayName: 'سارا مالی',
        buildingId: 'bld-diyar',
        status: 'active',
      },
    ],
    complexes: [
      {
        id: 'cpx-minoodar',
        name: 'شهرک مینودر',
        city: 'قزوین',
        managerName: 'مریم کاظمی',
        username: 'complex',
        password: 'complex123',
        blockIds: ['bld-diyar', 'bld-aftab'],
        status: 'active',
      },
    ],
    teams: [
      {
        id: 'team-elev',
        complexId: 'cpx-minoodar',
        name: 'تیم آسانسور',
        specialty: 'آسانسور و بالابر',
      },
      {
        id: 'team-elec',
        complexId: 'cpx-minoodar',
        name: 'تیم برق',
        specialty: 'برق مشاعات',
      },
      {
        id: 'team-clean',
        complexId: 'cpx-minoodar',
        name: 'تیم نظافت',
        specialty: 'نظافت و فضای سبز',
      },
    ],
    tickets: [
      {
        id: 'tkt1',
        complexId: 'cpx-minoodar',
        buildingId: 'bld-diyar',
        category: 'آسانسور',
        title: 'صدای غیرعادی کابین',
        body: 'از هفته گذشته هنگام توقف طبقه ۲ صدای سایش شنیده می‌شود.',
        status: 'open',
        createdBy: 'حسین توکلی (مدیر بلوک)',
        createdAt: daysAgo(2),
        updatedAt: daysAgo(2),
      },
      {
        id: 'tkt2',
        complexId: 'cpx-minoodar',
        buildingId: 'bld-aftab',
        category: 'برق',
        title: 'خاموشی چراغ‌های حیاط',
        body: 'نیمی از چراغ‌های بلوک ب خاموش است؛ درخواست اعزام تیم برق.',
        status: 'in_progress',
        createdBy: 'علی رضایی (مدیر بلوک)',
        assignedTeamId: 'team-elec',
        createdAt: daysAgo(5),
        updatedAt: daysAgo(1),
      },
      {
        id: 'tkt3',
        complexId: 'cpx-minoodar',
        buildingId: 'bld-diyar',
        category: 'نظافت',
        title: 'لکه روغن پارکینگ',
        body: 'لکه روغن در رمپ پارکینگ نیاز به پاکسازی تخصصی دارد.',
        status: 'resolved',
        createdBy: 'حسین توکلی (مدیر بلوک)',
        assignedTeamId: 'team-clean',
        createdAt: daysAgo(12),
        updatedAt: daysAgo(4),
        resolutionNote: 'تیم نظافت لکه را پاک کرد.',
      },
    ],
    discounts: [
      {
        id: 'dc1',
        code: 'DIYAR20',
        percent: 20,
        maxUses: 50,
        usedCount: 3,
        active: true,
        note: 'تخفیف افتتاحیه',
      },
      {
        id: 'dc2',
        code: 'TOWER10',
        percent: 10,
        maxUses: 100,
        usedCount: 12,
        active: true,
        note: 'ویژه برج‌ها',
      },
    ],
    tariffs: [
      {
        id: 'tr1',
        name: 'کوچک',
        maxUnits: 10,
        monthlyPerUnit: 45_000,
        buildingTypes: ['block', 'building'],
      },
      {
        id: 'tr2',
        name: 'متوسط',
        maxUnits: 30,
        monthlyPerUnit: 38_000,
        buildingTypes: ['block', 'building', 'tower'],
      },
      {
        id: 'tr3',
        name: 'بزرگ',
        maxUnits: 80,
        monthlyPerUnit: 32_000,
        buildingTypes: ['building', 'tower'],
      },
      {
        id: 'tr4',
        name: 'برج',
        maxUnits: 9999,
        monthlyPerUnit: 28_000,
        buildingTypes: ['tower'],
      },
    ],
    subscriptionPayments: [
      {
        id: 'sp1',
        buildingId: 'bld-diyar',
        amount: 1_800_000,
        units: 4,
        months: 12,
        method: 'gateway',
        status: 'paid_demo',
        trackingCode: 'SUB-8821',
        createdAt: daysAgo(20),
      },
      {
        id: 'sp2',
        buildingId: 'bld-sepehr',
        amount: 12_500_000,
        units: 48,
        months: 6,
        discountCode: 'TOWER10',
        method: 'bank_receipt',
        status: 'pending',
        receiptNote: 'فیش کارت‌به‌کارت — بانک ملی',
        trackingCode: 'SUB-9910',
        createdAt: daysAgo(1),
      },
      {
        id: 'sp3',
        buildingId: 'bld-aftab',
        amount: 1_200_000,
        units: 12,
        months: 3,
        method: 'bank_receipt',
        status: 'approved',
        receiptNote: 'فیش آپلود‌شده توسط مدیر بلوک',
        trackingCode: 'SUB-7744',
        createdAt: daysAgo(8),
        reviewedAt: daysAgo(7),
        reviewedBy: 'مدیر بلوک آفتاب',
      },
    ],
    sms: {
      enabled: false,
      endpoint: 'https://sms.example.com/api/send',
      apiKey: '',
      sender: 'DiyarSharj',
    },
    gateway: {
      mode: 'both',
      merchantId: '',
      callbackUrl: 'https://sharj.diyareminoodari.ir/pay/callback',
      bankAccountInfo: 'بانک ملت — شماره شبا IR00•••••••• — به نام دیارشارژ',
      enabled: true,
    },
    activity: [
      { id: 'act1', at: daysAgo(0), kind: 'login', label: 'ورود مدیر سایت', buildingId: undefined },
      { id: 'act2', at: daysAgo(1), kind: 'payment', label: 'فیش اشتراک برج سپهر ثبت شد', buildingId: 'bld-sepehr' },
      { id: 'act3', at: daysAgo(2), kind: 'ticket', label: 'تیکت آسانسور از دیار مینودری', buildingId: 'bld-diyar' },
      { id: 'act4', at: daysAgo(3), kind: 'qarz', label: 'صندوق قرض‌الحسنه در انتظار رأی', buildingId: 'bld-diyar' },
      { id: 'act5', at: daysAgo(4), kind: 'ticket', label: 'تیکت برق بلوک آفتاب به تیم ارجاع شد', buildingId: 'bld-aftab' },
      { id: 'act6', at: daysAgo(5), kind: 'sub', label: 'پرداخت اشتراک دیار مینودری', buildingId: 'bld-diyar' },
      { id: 'act7', at: daysAgo(6), kind: 'feature', label: 'فعال‌سازی ماژول پیشنهادات', buildingId: 'bld-aftab' },
      { id: 'act8', at: daysAgo(8), kind: 'payment', label: 'تأیید فیش اشتراک آفتاب', buildingId: 'bld-aftab' },
    ],
  }
}
