<?php
/**
 * Persist gateway settings to config.php (or outside-webroot path if writable).
 * Merchant ID never returned in full — only masked confirmation.
 */
require __DIR__ . '/bootstrap.php';

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
    zp_respond(405, ['ok' => false, 'message' => 'POST required']);
}

$cfg = zp_load_config();
$body = zp_json_body();

$token = (string) ($_SERVER['HTTP_X_ADMIN_TOKEN'] ?? $body['admin_token'] ?? '');
if ($cfg['admin_token'] !== '' && !hash_equals($cfg['admin_token'], $token)) {
    zp_respond(401, ['ok' => false, 'message' => 'admin_token نامعتبر']);
}

$merchant = trim((string) ($body['merchant_id'] ?? ''));
if ($merchant === '' || strcasecmp($merchant, 'unchanged') === 0) {
    $merchant = $cfg['merchant_id'];
}
if ($merchant !== '' && !zp_merchant_ok($merchant)) {
    zp_respond(400, ['ok' => false, 'message' => 'فرمت Merchant ID نامعتبر (UUID سی‌وشش کاراکتری)']);
}

$next = [
    'merchant_id' => $merchant,
    'sandbox' => array_key_exists('sandbox', $body) ? (bool) $body['sandbox'] : $cfg['sandbox'],
    'enabled' => array_key_exists('enabled', $body) ? (bool) $body['enabled'] : $cfg['enabled'],
    'currency' => (isset($body['currency']) && strtoupper((string) $body['currency']) === 'IRR') ? 'IRR' : 'IRT',
    'callback_url' => trim((string) ($body['callback_url'] ?? $cfg['callback_url'])),
    'admin_token' => $cfg['admin_token'],
];

$target = $cfg['_config_path'] ?? null;
if (!$target || !empty($cfg['_using_example'])) {
    $outside = dirname(__DIR__, 3) . '/zarinpal-config.php';
    $local = __DIR__ . '/config.php';
    $target = is_writable(dirname($outside)) ? $outside : $local;
}

$export = "<?php\n// Generated by save-config.php — do not commit secrets\nreturn "
    . var_export($next, true)
    . ";\n";

if (@file_put_contents($target, $export) === false) {
    zp_respond(500, [
        'ok' => false,
        'message' => 'نتوانستیم config را بنویسیم. دستی config.example.php را به config.php کپی کنید.',
        'tried_path' => basename($target),
    ]);
}

$masked = strlen($merchant) >= 8 ? substr($merchant, 0, 4) . '…' . substr($merchant, -4) : '';
zp_respond(200, [
    'ok' => true,
    'message' => 'تنظیمات درگاه ذخیره شد',
    'path_hint' => strpos($target, 'public_html') !== false || strpos($target, '/api/zarinpal/') !== false
        ? 'api/zarinpal/config.php'
        : 'outside webroot (zarinpal-config.php)',
    'enabled' => $next['enabled'],
    'sandbox' => $next['sandbox'],
    'currency' => $next['currency'],
    'callback_url' => $next['callback_url'],
    'merchant_masked' => $masked,
    'merchant_configured' => zp_merchant_ok($merchant),
]);
